// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/getsticker/domain"
	mock "github.com/stretchr/testify/mock"
)

// StickerRepository is an autogenerated mock type for the StickerRepository type
type StickerRepository struct {
	mock.Mock
}

// GetStickers provides a mock function with given fields:
func (_m *StickerRepository) GetStickers() (*[]domain.Sticker, error) {
	ret := _m.Called()

	var r0 *[]domain.Sticker
	if rf, ok := ret.Get(0).(func() *[]domain.Sticker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Sticker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStickerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewStickerRepository creates a new instance of StickerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStickerRepository(t mockConstructorTestingTNewStickerRepository) *StickerRepository {
	mock := &StickerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
