version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
 
  go:
    container_name: go
    build:
      context: .
    depends_on:
      - postgres          
 
    

volumes:
  database_postgres:                  